// AUTO-GENERATED — DO NOT EDIT THIS FILE.
//
// Generated from github.com/kayushkin/tool-store @ b214c5aed748aa3b70878f1aaad6196bf6141c9e
// Source of truth: the Go types named in tygo.yaml.
// To regenerate: ./generate-ts.sh
//
// Any manual changes will be overwritten on the next generation run.

// Code generated by tygo. DO NOT EDIT.

//////////
// source: provision.go

/**
 * ProvisionRequest says which tools to provision, in one of three ways.
 * Name them outright — by id in ToolIDs, or by name in Tools — or name an
 * instance in InstanceID and let the store read that instance's opt-in list
 * (the rows the Tools page writes through /instances/{id}/tools/by-name/{name}).
 * Exactly one of the three must be set: an empty request is an error — the
 * caller must say what it wants, no implicit "all" — and a request carrying
 * more than one is an error too, because merging a standing preference with
 * a per-call list gives the same field two sources of truth.
 * ToolIDs is the form for a caller that already holds ids from another store
 * — llm-bridge-server, intersecting a principal's grants with an instance's
 * opt-ins, has ids on both sides and no reason to go through a name.
 */
export interface ProvisionRequest {
  tools: string[];
  tool_ids: number /* int64 */[];
  instance_id: string;
}
/**
 * ProvisionResponse mirrors the shape Claude Code expects in --mcp-config:
 * 	{ "mcpServers": { "<name>": { "command": ..., "args": ..., "env": {...} } } }
 * For non-stdio MCP servers, "command" is omitted and "url" + "type" describe
 * the http/sse endpoint instead.
 */
export interface ProvisionResponse {
  mcpServers?: { [key: string]: MCPServerConfig};
}
/**
 * MCPServerConfig is a single entry under "mcpServers". Field choice depends
 * on the source MCPSpec.Transport.
 */
export interface MCPServerConfig {
  command?: string;
  args?: string[];
  env?: { [key: string]: string};
  url?: string;
  type?: string;
}

//////////
// source: tool.go

export type Kind = string;
export const KindMCP: Kind = "mcp";
export const KindCLI: Kind = "cli";
export const KindLocal: Kind = "local";
/**
 * Tool is a registry entry. Exactly one of MCP/CLI/Local is populated based on
 * Kind. EnvKeys lists required environment variable *names* — values are
 * resolved at provision time from the canonical credential source, never
 * stored here. Credentials (optional) maps each env-var name to the
 * auth-store provider that owns its value; entries with no mapping must be
 * resolved by the caller out of band (and provisioning fails if neither path
 * produces a value — no silent fallback).
 */
export interface Tool {
  id: number /* int64 */;
  name: string;
  display_name?: string;
  description: string;
  kind: Kind;
  input_schema?: unknown;
  env_keys?: string[];
  credentials?: { [key: string]: string};
  tags?: string[];
  mcp?: MCPSpec;
  cli?: CLISpec;
  local?: LocalSpec;
  enabled: boolean;
  created_at: number /* int64 */;
  updated_at: number /* int64 */;
}
/**
 * MCPSpec describes how to launch or reach an MCP server.
 */
export interface MCPSpec {
  transport: string; // stdio | http | sse
  command?: string; // stdio
  args?: string[]; // stdio
  url?: string; // http | sse
}
/**
 * CLISpec describes an arbitrary command-line tool. ArgsTemplate elements may
 * contain {{var}} placeholders that are substituted from the JSON-decoded input
 * at invocation time.
 */
export interface CLISpec {
  command: string;
  args_template?: string[];
  working_dir?: string;
  timeout_ms?: number /* int */;
}
/**
 * LocalSpec describes a Go function registered into the tool-store binary at
 * build time. Symbol is the canonical name (e.g. "agentkit/tools.Shell") used
 * to look up the implementation in the in-process registry.
 */
export interface LocalSpec {
  symbol: string;
}
/**
 * LocalDescriptor describes one in-process registered local tool — what's
 * available to be enabled via POST /tools.
 */
export interface LocalDescriptor {
  name: string;
  description: string;
  input_schema?: unknown;
}
