// AUTO-GENERATED — DO NOT EDIT THIS FILE.
//
// Generated from github.com/kayushkin/tool-store @ 888080e3b85db21e3ac116680fa046a1779654d9
// Source of truth: the Go types named in tygo.yaml.
// To regenerate: ./generate-ts.sh
//
// Any manual changes will be overwritten on the next generation run.

// Code generated by tygo. DO NOT EDIT.

//////////
// source: harness_observed.go

/**
 * TagUnreviewed marks a harness tool that a harness reported and nobody has
 * reviewed yet. RecordObservedHarnessTools creates such rows switched off; a
 * person reviews one by replacing its tags (PATCH /tools/{id}) and, if it
 * should be on, enabling it (POST /tools/{id}/enable).
 */
export const TagUnreviewed = "unreviewed";
/**
 * ObservedHarnessToolsRequest is the body of POST /harness-tools/observed: the
 * built-in tool names one harness reported at the start of a session. Harness
 * is llm-bridge-server's harness id, passed through as sent.
 */
export interface ObservedHarnessToolsRequest {
  harness: string;
  tool_names: string[];
}
/**
 * ObservedHarnessToolsResponse answers POST /harness-tools/observed. Created
 * lists the reported names that had no row and now have one, switched off and
 * tagged unreviewed; Seen counts the distinct names whose last_seen_at was set.
 */
export interface ObservedHarnessToolsResponse {
  created: string[];
  seen: number /* int */;
}
/**
 * ToolPatch is the body of PATCH /tools/{id}: the fields a person changes when
 * reviewing a tool. A nil field is left as it is. Tags replaces the whole
 * list.
 */
export interface ToolPatch {
  tags?: string[];
  description?: string;
  enabled?: boolean;
}

//////////
// source: provision.go

/**
 * ProvisionRequest says which tools to provision, in one of three ways.
 * Name them outright — by id in ToolIDs, or by name in Tools — or name an
 * instance in InstanceID and let the store read that instance's opt-in list
 * (the rows the Tools page writes through /instances/{id}/tools/by-name/{name}).
 * Exactly one of the three must be set: an empty request is an error — the
 * caller must say what it wants, no implicit "all" — and a request carrying
 * more than one is an error too, because merging a standing preference with
 * a per-call list gives the same field two sources of truth.
 * ToolIDs is the form for a caller that already holds ids from another store
 * — llm-bridge-server, intersecting a principal's grants with an instance's
 * opt-ins, has ids on both sides and no reason to go through a name.
 */
export interface ProvisionRequest {
  tools: string[];
  tool_ids: number /* int64 */[];
  instance_id: string;
}
/**
 * ProvisionResponse mirrors the shape Claude Code expects in --mcp-config:
 * 	{ "mcpServers": { "<name>": { "command": ..., "args": ..., "env": {...} } } }
 * For non-stdio MCP servers, "command" is omitted and "url" + "type" describe
 * the http/sse endpoint instead.
 */
export interface ProvisionResponse {
  mcpServers?: { [key: string]: MCPServerConfig};
}
/**
 * MCPServerConfig is a single entry under "mcpServers". Field choice depends
 * on the source MCPSpec.Transport.
 */
export interface MCPServerConfig {
  command?: string;
  args?: string[];
  env?: { [key: string]: string};
  url?: string;
  type?: string;
}

//////////
// source: tool.go

export type Kind = string;
export const KindMCP: Kind = "mcp";
export const KindCLI: Kind = "cli";
export const KindLocal: Kind = "local";
export const KindHarness: Kind = "harness";
/**
 * KindDescriptor is one entry of the kind vocabulary served on GET /kinds.
 */
export interface KindDescriptor {
  kind: Kind;
  description: string;
}
/**
 * Tool is a registry entry. Exactly one of MCP/CLI/Local is populated based on
 * Kind; a kind=harness tool has none of them and carries Harness (the
 * llm-bridge harness id, e.g. "claude_code" or "codex") and HarnessToolName
 * (the name the harness itself uses, e.g. "Read"), which every other kind
 * leaves empty. EnvKeys lists required environment variable *names* — values are
 * resolved at provision time from the canonical credential source, never
 * stored here. Credentials (optional) maps each env-var name to the
 * auth-store provider that owns its value; entries with no mapping must be
 * resolved by the caller out of band (and provisioning fails if neither path
 * produces a value — no silent fallback).
 */
export interface Tool {
  id: number /* int64 */;
  name: string;
  display_name?: string;
  description: string;
  kind: Kind;
  input_schema?: unknown;
  env_keys?: string[];
  credentials?: { [key: string]: string};
  tags?: string[];
  harness?: string;
  harness_tool_name?: string;
  /**
   * LastSeenAt is when a harness last reported this tool in its session's
   * tool list (POST /harness-tools/observed), in unix seconds; 0 means never
   * reported. Only that route writes it: POST /tools and seeding leave it.
   */
  last_seen_at: number /* int64 */;
  mcp?: MCPSpec;
  cli?: CLISpec;
  local?: LocalSpec;
  enabled: boolean;
  created_at: number /* int64 */;
  updated_at: number /* int64 */;
}
/**
 * MCPSpec describes how to launch or reach an MCP server.
 */
export interface MCPSpec {
  transport: string; // stdio | http | sse
  command?: string; // stdio
  args?: string[]; // stdio
  url?: string; // http | sse
}
/**
 * CLISpec describes an arbitrary command-line tool. ArgsTemplate elements may
 * contain {{var}} placeholders that are substituted from the JSON-decoded input
 * at invocation time.
 */
export interface CLISpec {
  command: string;
  args_template?: string[];
  working_dir?: string;
  timeout_ms?: number /* int */;
}
/**
 * LocalSpec describes a Go function registered into the tool-store binary at
 * build time. Symbol is the canonical name (e.g. "agentkit/tools.Shell") used
 * to look up the implementation in the in-process registry.
 */
export interface LocalSpec {
  symbol: string;
}
/**
 * LocalDescriptor describes one in-process registered local tool — what's
 * available to be enabled via POST /tools.
 */
export interface LocalDescriptor {
  name: string;
  description: string;
  input_schema?: unknown;
}
